language: node_js

node_js:
  - 8 # LTS as of 2017
  - node # latest

script:
  - npm run test:coverage
  - npm run cypress:test

notifications:
  email:
    on_failure: change

after_success: 'npm run coveralls'

cache:
  yarn: true
  directories:
    - node_modules
